title: Seraph
subtitle: Research • Build • Protect.
description: Cybersecurity, home lab, medical technology, IoT, and web development.
keywords: 資安, CTF, Web, Robotics, IoT
author: Seraph
language: en
timezone: Asia/Taipei

url: https://seraphforge.github.io/seraphforge.tw
root: /seraphforge.tw/

theme: landscape

deploy:
  type: git
  repo: https://github.com/seraphforge/seraphforge.github.io.git
  branch: gh-pages

feed:
  type: atom
  path: feed.xml
  limit: 20

sitemap:
  path: sitemap.xml
  template: ./sitemap_template.xml
